// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVCaW-SjQfpK2742OSu95o0Jqsjf32CnM',
    appId: '1:1065291315046:web:3c496ee70f001d1b907aa7',
    messagingSenderId: '1065291315046',
    projectId: 'trabalhomoveis-92e6f',
    authDomain: 'trabalhomoveis-92e6f.firebaseapp.com',
    storageBucket: 'trabalhomoveis-92e6f.appspot.com',
    measurementId: 'G-1J0M3L7Q7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFqHnahOdMVTglttc-dS4lhFU5sDpcsIU',
    appId: '1:1065291315046:android:93c7199096a2e151907aa7',
    messagingSenderId: '1065291315046',
    projectId: 'trabalhomoveis-92e6f',
    storageBucket: 'trabalhomoveis-92e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6uciCAhFWlLY5BIwWxpTui6urHTOOi9s',
    appId: '1:1065291315046:ios:89b553c78e29fafd907aa7',
    messagingSenderId: '1065291315046',
    projectId: 'trabalhomoveis-92e6f',
    storageBucket: 'trabalhomoveis-92e6f.appspot.com',
    iosClientId: '1065291315046-fc8gl0f176p1ds1ad9jjafn92duj1uko.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalhoFinalProgMoveis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6uciCAhFWlLY5BIwWxpTui6urHTOOi9s',
    appId: '1:1065291315046:ios:854abb7eb7a4d0bb907aa7',
    messagingSenderId: '1065291315046',
    projectId: 'trabalhomoveis-92e6f',
    storageBucket: 'trabalhomoveis-92e6f.appspot.com',
    iosClientId: '1065291315046-1nqagb46u0miqpmdsqbl0ab2fvip33h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalhoFinalProgMoveis.RunnerTests',
  );
}
